version: "0.0"
services:
  web:
    build: .
    ports:
      - "8081:3000"
    environment:
      - SERVER_URL=http://web:3000
      - CORS_URL=http://web:8080
      - POSTGRES_URL=postgresql://postgres:postgrespassword@postgres:5432
      - DATABASE_URL=postgresql://postgres:postgrespassword@postgres:5432
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_USER=postgres
