version: "0.0"
services:
  web:
    build: .
    ports:
      - "${LOCAL_CLIENT_PORT}:${SERVER_PORT}"
    env_file:
      - .env
      - .env.production

  postgres:
    image: "postgres"
    env_file:
      - .env
      - .env.production
